"""Day 5's session, as one page: a paper published so that a machine can read
it, and the same idea run at laptop scale in three directories.

What they launch, at minute zero &middot; the release, one file at a time:
the argument skeleton, the working wiki it came out of, the provenance layer
in the prose, the gate, and the reproducibility section &middot; a second
release by other people, briefly &middot; the tool that was sitting in two of
their three directories &middot; what the three cells left, and the turn where
the gate fired &middot; what we make of it &middot; back to your three
directories. A student who opens this one file has the hour.

The organising line is the hour's whole claim: content written down for a
machine to read is available now and was not before. Matias, 2026-08-18: "A
standard part of reading a paper is trying to figure out what the claims are
and what the evidence is. Why have to guess? We can say it explicitly and the
agents can understand it."

The axis is the one nothing else in the week varies. Day 2 varied the model,
day 3 the contract, day 4 how well posed the question was. Here the task, the
model and the command are held fixed and WHAT SITS IN THE DIRECTORY MOVES:
nothing, a skill and a hook, the hook only.

Built by `code/build_show.py` against `code/show_template.html`, synced into
`course/` by `code/day5/make_day.py`, which fails if that copy differs.

THIS PAGE COMPUTES NOTHING. The three cells finished before it was written and
the release was published before that; nothing here re-runs an agent, re-times
anything, or recomputes a number from the paper. Its one generated input is

    score_cells.py     read runs/, release/, the scaffold and readings.json;
                       write meta.json for each cell, the provenance.json every
                       [src:] below resolves in, prompts.txt, the embedded
                       pages and the tables
"""

TITLE = "A paper a machine can read — day 5, the practical session"
WHO = "Day 5 &middot; the practical session"
OUT = "session-ai5.html"
SYNC = "course/day5/session-ai5.html"

# One prompt, and it is the one the room types. `prompts.txt` is assembled by
# score_cells.py out of the scaffold's own PROMPT.txt and checked against the
# first user message of each archived transcript, so the page shows what the
# cells were actually given.
N_PROMPTS = 1

# Three cells: the same task, the same model, the same command, and only what
# sat in the directory beforehand differs.
RUNS = ["runs/a", "runs/b", "runs/c"]

# Rule 1c. Every [src:key] on a stage resolves here or the build fails. The
# registry is generated by score_cells.py out of the archive, the scaffold and
# the release copies, so a number on this page is a number in a file.
REGISTRIES = ["code/day5/show/provenance.json"]

# NO FIGURE OF OURS, as on days 3 and 4. The figures on this page are the
# cells' own, whole, inside the embedded pages of what each cell left.
IMAGES = {}

# Generated by score_cells.py and spliced where a stage writes __INCLUDE_key__.
INCLUDES = {
    "cells": "inc-cells.html",
    "scaffold": "inc-scaffold.html",
    "release": "inc-release.html",
    "runtags": "inc-runtags.html",
}

# Base64 into VIZ, mounted into an iframe only when the reader picks it.
#
# The release files are shown WHOLE, one page each, generated from copies taken
# on 2026-08-18 (release/SOURCES.md says where each came from). The repository
# is private as this is built, so nothing here is a link; the copies exist so
# every quote on the page is re-read out of a file at build time.
#
# Each cell's page carries the reply and every file the cell left, unedited:
# text as text, a figure as itself. Cell c has one page more — the turn where
# its gate fired, out of the transcript.
EMBED = {
    # the release, in the order the hour shows it
    "release-claims": "code/day5/show/assets/release-claims.html",
    "release-conventions": "code/day5/show/assets/release-conventions.html",
    "release-sty": "code/day5/show/assets/release-sty.html",
    "release-tex": "code/day5/show/assets/release-tex.html",
    "release-check": "code/day5/show/assets/release-check.html",
    "release-numbers": "code/day5/show/assets/release-numbers.html",
    "release-readme": "code/day5/show/assets/release-readme.html",
    "lensing-readme": "code/day5/show/assets/lensing-readme.html",

    # the scaffold the room runs
    "scaffold-skill": "code/day5/show/assets/scaffold-skill.html",
    "scaffold-md": "code/day5/show/assets/scaffold-md.html",
    "scaffold-hook": "code/day5/show/assets/scaffold-hook.html",
    "scaffold-wiring": "code/day5/show/assets/scaffold-wiring.html",

    # the three cells
    "cell-a": "code/day5/show/assets/cell-a-files.html",
    "cell-b": "code/day5/show/assets/cell-b-files.html",
    "cell-c": "code/day5/show/assets/cell-c-files.html",
    "cell-c-hook": "code/day5/show/assets/cell-c-hook-turn.html",
}
